name: Data Updating

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công trên GitHub

jobs:
  update-and-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Data
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python -m src.ingestion

    - name: Preprocess Data
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python -m src.preprocess

    - name: Download Models
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DRIVE_ID_SCALER: ${{ secrets.DRIVE_ID_SCALER }}
        DRIVE_ID_TRAINING_DATA: ${{ secrets.DRIVE_ID_TRAINING_DATA }}
        DRIVE_ID_RF: ${{ secrets.DRIVE_ID_RF }}
        DRIVE_ID_LSTM: ${{ secrets.DRIVE_ID_LSTM }}
      run: python -m src.scripts.download_model

    - name: Inference
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: python -m src.inference

    - name: Notify Status
      if: always()
      run: echo "Pipeline finished with status ${{ job.status }}"
